import { Decision } from "./decision.js";
import { ExecutionEvidence } from "./execution-evidence.js";
import { ExecutionMetadata } from "./execution-metadata.js";
import type { Signature } from "./signature.js";

/**
 * Parmana Trust Core
 *
 * Execution
 *
 * Records what actually happened while processing a
 * Business Transaction.
 *
 * Every Execution records exactly one immutable
 * Decision produced by deterministic Policy
 * evaluation.
 *
 * Executions are immutable trust artifacts and
 * become part of the Execution Trust Record.
 */
export interface Execution {
  /**
   * Unique Execution identifier.
   */
  readonly executionId: string;

  /**
   * Business Transaction to which this Execution belongs.
   */
  readonly businessTransactionId: string;

  /**
   * Immutable Decision produced by this Execution.
   *
   * The Decision is generated by evaluating the
   * referenced Policy against the supplied runtime
   * signals.
   */
  readonly decision: Decision;

  /**
   * Execution lifecycle state.
   */
  readonly status: ExecutionStatus;

  /**
   * Execution mode.
   */
  readonly mode: ExecutionMode;

  /**
   * UTC timestamp when execution started.
   */
  readonly startedAt: Date;

  /**
   * UTC timestamp when execution completed.
   *
   * Present only for terminal executions.
   */
  readonly completedAt?: Date;

  /**
   * Immutable execution evidence.
   */
  readonly evidence?: ExecutionEvidence;

  /**
   * Execution-specific metadata.
   */
  readonly metadata?: ExecutionMetadata;

  /**
   * chainHash of the chain predecessor -- the prior Execution
   * belonging to the same businessTransactionId -- or null for the
   * first Execution in that transaction's chain. Fixed once, at this
   * Execution's first creation; unlike chainHash/chainSignature, it
   * does not change across this row's own lifecycle transitions
   * (see ExecutionChainCrypto in @parmana/crypto).
   *
   * Optional so every pre-existing construction site and historical
   * row (written before this field existed) keeps compiling and
   * verifying unchanged -- an absent value means "not chain-
   * protected," not "broken chain."
   */
  readonly previousChainHash?: string | null;

  /**
   * Signed hash of this Execution's own canonical content plus
   * previousChainHash. Recomputed on every legitimate mutation of
   * this row (attachEvidence/complete/fail), since those change what
   * this hash covers.
   */
  readonly chainHash?: string;

  /**
   * Digital signature over the same canonical content chainHash was
   * computed from. Signed with Parmana's own signing key, so an
   * actor with database write access but not the private key cannot
   * forge a replacement chainHash/chainSignature pair -- see
   * ExecutionChainCrypto.
   */
  readonly chainSignature?: Signature;
}

/**
 * Canonical execution lifecycle.
 */
export enum ExecutionStatus {
  PROCESSING = "PROCESSING",

  COMPLETED = "COMPLETED",

  FAILED = "FAILED",
}

/**
 * Execution mode.
 */
export enum ExecutionMode {
  SYNC = "SYNC",

  ASYNC = "ASYNC",
}